import esbuild from "esbuild";
import process from "process";
import fs from "fs/promises";
import builtins from "builtin-modules";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");


const patchMarked = {
	name: "patch-marked",
	setup(build) {
		build.onLoad({ filter: /marked\.esm\.js$/ }, async (args) => {
			let contents = await fs.readFile(args.path, "utf8");
			contents = contents.replace(/\\x00-\\x1f/g, "");
			contents = contents.replace(/\\u0000-\\u001f/g, "");
			return { contents, loader: "js" };
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	plugins: [patchMarked],
	outfile: "main.js",
	minify: prod,
	loader: {
		".css": "text"
	},
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
